In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 200)

In [3]:
data_path = "dataset/H_MHAS_c2.dta" 
df = pd.read_stata(data_path)

In [4]:
df.shape

(26839, 5241)

In [5]:
df.head(5)

codent01                             codent03  ps3  \
0            1.Selected person            1.Selected person in 2001  1.0   
1  2.Spouse of selected person  2.Spouse of selected person in 2001  2.0   
2            1.Selected person            1.Selected person in 2001  1.0   
3  2.Spouse of selected person  2.Spouse of selected person in 2001  2.0   
4            1.Selected person            1.Selected person in 2001  1.0   

   ent2  np  unhhidnp rahhidnp                    tipent_01  \
0   1.0  10     110.0      110  12.Direct, second interview   
1   2.0  20     120.0      120   11.Direct, first interview   
2   1.0  10     210.0      210   11.Direct, first interview   
3   2.0  20     220.0      220  12.Direct, second interview   
4   1.0  10     310.0      310   11.Direct, first interview   

                     tipent_03                      tipent_12  \
0  12.Direct, second interview  1.Direct, follow-up interview   
1   11.Direct, first interview  1.Direct, follow-up interview   
2   22.Proxy, second interview  1.Direct, follow-up interview   
3   11.Direct, first interview   3.Proxy, follow-up interview   
4   11.Direct, first interview  1.Direct, follow-up interview   

                       tipent_15                      tipent_18  unhhid  \
0                            NaN                            NaN       1   
1  1.Direct, follow-up interview  1.Direct, follow-up interview       1   
2  1.Direct, follow-up interview  1.Direct, follow-up interview       2   
3   3.Proxy, follow-up interview                            NaN       2   
4  1.Direct, follow-up interview  1.Direct, follow-up interview       3   

   cunicah  h1hhid  h2hhid  h3hhid  h4hhid  h5hhid h1hhidc h2hhidc h3hhidc  \
0        1    10.0    11.0    11.0    41.0   109.0      10      11      11   
1        1    10.0    11.0    11.0    22.0    22.0      10      11      11   
2        2    20.0    21.0    21.0    21.0    31.0      20      21      21   
3        2    20.0    21.0    21.0    21.0    52.0      20      21      21   
4        3    30.0    41.0    31.0    31.0    31.0      30      41      31   

  h4hhidc h5hhidc acthog       subhog_01                         subhog_03  \
0      41     109     00  00.Baseline HH  01.No change, HH contains NP=010   
1      22      22     00  00.Baseline HH  01.No change, HH contains NP=010   
2      21      31     00  00.Baseline HH  01.No change, HH contains NP=010   
3      21      52     00  00.Baseline HH  01.No change, HH contains NP=010   
4      31      31     01  00.Baseline HH         11.New HH contains NP=010   

                          subhog_12                         subhog_15  \
0  01.No change, HH contains NP=010                31.NP=010 Deceased   
1  01.No change, HH contains NP=010         12.New HH contains NP=020   
2  01.No change, HH contains NP=010  01.No change, HH contains NP=010   
3  01.No change, HH contains NP=010  01.No change, HH contains NP=010   
4  01.No change, HH contains NP=010  01.No change, HH contains NP=010   

                          subhog_18  s1hhidnp  s2hhidnp  s3hhidnp  s4hhidnp  \
0          99.Not part of the study     120.0     120.0     120.0       NaN   
1         12.New HH contains NP=020     110.0     110.0     110.0       NaN   
2         11.New HH contains NP=010     220.0     220.0     220.0     220.0   
3                32.NP=020 Deceased     210.0     210.0     210.0     210.0   
4  01.No change, HH contains NP=010     311.0     311.0     311.0     311.0   

   s5hhidnp           inw1           inw2           inw3           inw4  \
0       NaN  1.Resp, alive  1.Resp, alive  1.Resp, alive    0.Non, resp   
1       NaN  1.Resp, alive  1.Resp, alive  1.Resp, alive  1.Resp, alive   
2       NaN  1.Resp, alive  1.Resp, alive  1.Resp, alive  1.Resp, alive   
3       NaN  1.Resp, alive  1.Resp, alive  1.Resp, alive  1.Resp, alive   
4     311.0  1.Resp, alive  1.Resp, alive  1.Resp, alive  1.Resp, alive   

            inw5       r1iwstat       r2i

In [6]:
column_names = list(df.columns.str.lower())
# column_names

In [7]:
df['unhhidnp'].describe()

count    2.683900e+04
mean     9.459864e+05
std      5.576727e+05
min      1.100000e+02
25%      4.707150e+05
50%      9.409100e+05
75%      1.385115e+06
max      2.021820e+06
Name: unhhidnp, dtype: float64

In [8]:
df['unhhidnp'].isna().sum()

0

In [9]:
# with open(r'column_names.txt', 'w') as fp:
#     fp.write('\n'.join(column_names))

In [26]:
target_columns = ['r1hosp1y',
 'r2hosp1y',
 'r3hosp1y',
 'r4hosp1y',
 'r5hosp1y']
target_columns_count = len(target_columns)

In [24]:
no_wave_columns = [
"unhhidnp",
"ragender",
]
no_wave_columns_count = len(no_wave_columns)

In [29]:
picked_columns = [

# Age at Interview (Months and Years)    
"r1agey",
"r2agey",
"r3agey",
"r4agey",
"r5agey",

# Self-Report of Health
"r1shlt",
"r2shlt",
"r3shlt",
"r4shlt",
"r5shlt",

# # Doctor Diagnosed Health Problems: Ever Have Condition
# "r1hibpe",
# "r2hibpe",
# "r3hibpe",
# "r4hibpe",
# "r5hibpe",
# "r1diabe",
# "r2diabe",
# "r3diabe",
# "r4diabe",
# "r5diabe",
# "r1cancre",
# "r2cancre",
# "r3cancre",
# "r4cancre",
# "r5cancre",
# "r1respe",
# "r2respe",
# "r3respe",
# "r4respe",
# "r5respe",
# "r1hrtatte",
# "r2hrtatte",
# "r3hrtatte",
# "r4hrtatte",
# "r5hrtatte",

# "r4hearte",
# "r5hearte",

# "r1stroke",
# "r2stroke",
# "r3stroke",
# "r4stroke",
# "r5stroke",
# "r1arthre",
# "r2arthre",
# "r3arthre",
# "r4arthre",
# "r5arthre",
# "s5arthre",

# RwBMI is the respondent's self-reported body mass index
"r1bmi",
"r2bmi",
"r3bmi",
"r4bmi",
"r5bmi",

# Health Behaviors: Physical Activity or Exercise
"r1vigact",
"r2vigact",
"r3vigact",
"r4vigact",
"r5vigact",

# # Health Behaviors: Smoking (Cigarettes)
# "r1smokev",
# "r2smokev",
# "r3smokev",
# "r4smokev",
# "r5smokev",
# "r1smoken",
# "r2smoken",
# "r3smoken",
# "r4smoken",
# "r5smoken",
# "r1smokef",
# "r2smokef",
# "r3smokef",
# "r4smokef",
# "r5smokef",
# "r1strtsmok",
# "r2strtsmok",
# "r3strtsmok",
# "r4strtsmok",
# "r5strtsmok",
# "r1quitsmok",
# "r2quitsmok",
# "r3quitsmok",
# "r4quitsmok",
# "r5quitsmok",

# # Health Behaviors: Preventive Care
# "r1cholst",
# "r2cholst",
# "r3cholst",
# "r4cholst",
# "r5cholst",
# "r3flusht",
# "r4flusht",
# "r5flusht",
# "r1breast",
# "r2breast",
# "r3breast",
# "r4breast",
# "r5breast",
# "r1mammog",
# "r2mammog",
# "r3mammog",
# "r4mammog",
# "r5mammog",
# "r1papsm",
# "r2papsm",
# "r3papsm",
# "r4papsm",
# "r5papsm",
# "r1prost",
# "r2prost",
# "r3prost",
# "r4prost",
# "r5prost",
]

In [37]:
screening = no_wave_columns + target_columns + picked_columns
print(screening)

['unhhidnp', 'ragender', 'r1hosp1y', 'r2hosp1y', 'r3hosp1y', 'r4hosp1y', 'r5hosp1y', 'r1agey', 'r2agey', 'r3agey', 'r4agey', 'r5agey', 'r1shlt', 'r2shlt', 'r3shlt', 'r4shlt', 'r5shlt', 'r1bmi', 'r2bmi', 'r3bmi', 'r4bmi', 'r5bmi', 'r1vigact', 'r2vigact', 'r3vigact', 'r4vigact', 'r5vigact']


In [31]:
df_sub = df[screening]
df_sub.head(5)

unhhidnp ragender r1hosp1y r2hosp1y r3hosp1y r4hosp1y r5hosp1y  r1agey  \
0     110.0    1.Man    1.Yes     0.No     0.No      NaN      NaN    59.0   
1     120.0  2.Woman     0.No     0.No     0.No     0.No     0.No    50.0   
2     210.0    1.Man     0.No     0.No     0.No     0.No    1.Yes    69.0   
3     220.0  2.Woman     0.No     0.No     0.No    1.Yes      NaN    48.0   
4     310.0    1.Man     0.No     0.No     0.No     0.No     0.No    50.0   

   r2agey  r3agey  r4agey  r5agey  r1shlt       r2shlt  r3shlt  r4shlt  \
0    61.0    71.0     NaN     NaN  5.Poor  2.Very good  5.Poor     NaN   
1    52.0    62.0    65.0    68.0  4.Fair       4.Fair  3.Good  3.Good   
2    72.0    81.0    83.0    86.0  5.Poor          NaN  4.Fair  4.Fair   
3    50.0    70.0    74.0     NaN  3.Good       4.Fair     NaN     NaN   
4    53.0    62.0    65.0    68.0  3.Good       3.Good  4.Fair  3.Good   

   r5shlt      r1bmi      r2bmi      r3bmi      r4bmi      r5bmi r1vigact  \
0     NaN  29.068796        NaN  28.719721        NaN        NaN    1.Yes   
1  3.Good        NaN  20.239502        NaN  20.000000        NaN     0.No   
2  3.Good        NaN  39.262234        NaN  26.709404        NaN     0.No   
3     NaN        NaN  36.444443  22.038568        NaN        NaN     0.No   
4  3.Good  26.812220  22.437674  28.400547  29.411762  25.605536     0.No   

  r2vigact r3vigact r4vigact r5vigact  
0    1.Yes     0.No      NaN      NaN  
1     0.No     0.No     0.No     0.No  
2      NaN    1.Yes    1.Yes     0.No  
3     0.No      NaN      NaN      NaN  
4    1.Yes     0.No    1.Yes     0.No

In [38]:
wave_vars_orig_name = screening[no_wave_columns_count:]
print(wave_vars_orig_name)

['r1hosp1y', 'r2hosp1y', 'r3hosp1y', 'r4hosp1y', 'r5hosp1y', 'r1agey', 'r2agey', 'r3agey', 'r4agey', 'r5agey', 'r1shlt', 'r2shlt', 'r3shlt', 'r4shlt', 'r5shlt', 'r1bmi', 'r2bmi', 'r3bmi', 'r4bmi', 'r5bmi', 'r1vigact', 'r2vigact', 'r3vigact', 'r4vigact', 'r5vigact']


In [40]:
from collections import OrderedDict
wave_vars_clean_name = list(OrderedDict.fromkeys([name[2:] for name in wave_vars_orig_name])) # Remove the wave reference characters
wave_vars_clean_name

['hosp1y', 'agey', 'shlt', 'bmi', 'vigact']

In [41]:
from pprint import pprint

# Initialize an empty DataFrame with the desired final columns
# accumulated_df = pd.DataFrame(columns=final_columns)
accumulated_df = None

# Loop over the wave numbers
for wave in range(1, 6):
    # Create new column names for the current wave
    _names = [f"r{wave}{var}" for var in wave_vars_clean_name]
    wave_column_names = [name for name in _names if name in df_sub.columns] # Only keep valid column names
    # print(wave_column_names)
    column_mapping = {name: name[2:] for name in wave_column_names}  
    # print(column_mapping)

    # Select the necessary columns from the subset DataFrame and rename them
    wave_df = df_sub[no_wave_columns + wave_column_names].copy()
    wave_df = wave_df.rename(columns=column_mapping)

    # Insert the wave number as a new column
    wave_df.insert(0, "wave", wave)

    # Append the current wave's DataFrame to the accumulated DataFrame
    if accumulated_df is None:
        accumulated_df = wave_df.copy()
    else:
        accumulated_df = pd.concat([accumulated_df, wave_df])


In [42]:
accumulated_df.shape

(134195, 8)

In [43]:
accumulated_df.head()

wave  unhhidnp ragender hosp1y  agey    shlt        bmi vigact
0     1     110.0    1.Man  1.Yes  59.0  5.Poor  29.068796  1.Yes
1     1     120.0  2.Woman   0.No  50.0  4.Fair        NaN   0.No
2     1     210.0    1.Man   0.No  69.0  5.Poor        NaN   0.No
3     1     220.0  2.Woman   0.No  48.0  3.Good        NaN   0.No
4     1     310.0    1.Man   0.No  50.0  3.Good  26.812220   0.No

In [108]:
drop_first_columns_count = 2
accumulated_df.iloc[:,drop_first_columns_count:].head() # wave and unhhidnp are not needed

ragender hosp1y  agey    shlt        bmi vigact
0    1.Man  1.Yes  59.0  5.Poor  29.068796  1.Yes
1  2.Woman   0.No  50.0  4.Fair        NaN   0.No
2    1.Man   0.No  69.0  5.Poor        NaN   0.No
3  2.Woman   0.No  48.0  3.Good        NaN   0.No
4    1.Man   0.No  50.0  3.Good  26.812220   0.No

In [164]:
# Prepare new clean dataset
df_clean = accumulated_df.iloc[:,drop_first_columns_count:].dropna(subset=["hosp1y"]).copy()
print(df_clean.shape)
# Swap ragender with hosp1y column to better readability
cols = list(df_clean)  # Get a list of column names
cols[0], cols[1] = cols[1], cols[0]  # Swap the first two names
df_clean = df_clean.reindex(columns=cols)  # Reindex the DataFrame with the new column order

(76353, 6)


In [146]:
df_clean.head(5).T

0        1       2        3         4
hosp1y        1.Yes     0.No    0.No     0.No      0.No
ragender      1.Man  2.Woman   1.Man  2.Woman     1.Man
agey           59.0     50.0    69.0     48.0      50.0
shlt         5.Poor   4.Fair  5.Poor   3.Good    3.Good
bmi       29.068796      NaN     NaN      NaN  26.81222
vigact        1.Yes     0.No    0.No     0.No      0.No

In [147]:
df_clean.shape

(76353, 6)

In [165]:
df_clean.isna().sum()

hosp1y          0
ragender        0
agey           34
shlt         5727
bmi         13793
vigact       5847
dtype: int64

In [149]:
df_clean.dtypes

hosp1y      category
ragender    category
agey         float64
shlt        category
bmi          float32
vigact      category
dtype: object

In [150]:
df_clean.hosp1y.value_counts()

hosp1y
0.No     67160
1.Yes     9193
Name: count, dtype: int64

In [166]:
# Prepare target value
df_clean.hosp1y = (df_clean.hosp1y == "1.Yes").astype(int)

In [167]:
mapping = {'1.Excellent': 1, '2.Very good': 2, '3.Good': 3, '4.Fair': 4, '5.Poor': 5}
df_clean['shlt'] = df_clean['shlt'].map(mapping).astype(float)

In [168]:
from sklearn.model_selection import train_test_split

In [169]:
df_full_train, df_test = train_test_split(
    df_clean,
    test_size=0.2,
    random_state=1,
)

df_train, df_val = train_test_split(
    df_full_train,
    test_size= (0.2 / 0.8),
    random_state=1,
)

len(df_train), len(df_val), len(df_test)


(45811, 15271, 15271)

In [170]:
# Reset index and get y vectors
target = "hosp1y"

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train[target].values
y_val = df_val[target].values
y_test = df_test[target].values
        
del df_train[target] 
del df_val[target] 
del df_test[target] 

# EDA

In [171]:
df_full_train.shape

(61082, 6)

In [172]:
df_full_train = df_full_train.reset_index(drop=True)

In [173]:
df_full_train.hosp1y.value_counts(normalize=True)

hosp1y
0    0.880325
1    0.119675
Name: proportion, dtype: float64

In [174]:
global_hospitalization_rate = df_full_train.hosp1y.mean()
print(f"{global_hospitalization_rate:.2f}")

0.12


In [175]:
df_full_train.dtypes

hosp1y         int64
ragender    category
agey         float64
shlt         float64
bmi          float32
vigact      category
dtype: object

In [176]:
for col in df_full_train.columns:
    print(col)
    print(list(df_full_train[col].unique()))

hosp1y
[0, 1]
ragender
['2.Woman', '1.Man']
agey
[85.0, 65.0, 69.0, 88.0, 86.0, 51.0, 61.0, 76.0, 60.0, 50.0, 73.0, 75.0, 96.0, 68.0, 77.0, 57.0, 84.0, 64.0, 87.0, 54.0, 48.0, 47.0, 56.0, 70.0, 52.0, 81.0, 49.0, 58.0, 78.0, 71.0, 79.0, 67.0, 90.0, 44.0, 42.0, 83.0, 82.0, 46.0, 62.0, 63.0, 74.0, 43.0, 59.0, 89.0, 36.0, 66.0, 72.0, 53.0, 55.0, 80.0, 92.0, 34.0, 40.0, 41.0, 38.0, 99.0, 26.0, 31.0, 35.0, 45.0, 98.0, 37.0, nan, 91.0, 39.0, 24.0, 33.0, 97.0, 28.0, 93.0, 27.0, 95.0, 22.0, 32.0, 25.0, 104.0, 94.0, 101.0, 30.0, 110.0, 29.0, 21.0, 105.0, 100.0, 106.0, 107.0, 103.0, 18.0, 19.0, 115.0, 112.0, 23.0, 102.0]
shlt
[nan, 1.0, 3.0, 4.0, 5.0, 2.0]
bmi
[22.222221, 23.781212, 30.477968, nan, 35.196194, 22.0741, 28.305996, 26.666666, 35.50296, 22.714682, 23.4375, 27.54821, 25.777779, 26.037493, 33.59375, 21.428572, 29.32099, 24.973988, 28.650139, 23.529411, 35.840786, 23.671255, 25.510204, 24.567472, 25.28257, 27.942146, 39.001186, 30.222221, 26.927439, 25.23634, 25.529644, 28.935183, 38.56

In [177]:
df_full_train.dtypes.ne("category")

hosp1y       True
ragender    False
agey         True
shlt         True
bmi          True
vigact      False
dtype: bool

In [178]:
numerical = list(df_full_train.dtypes[df_full_train.dtypes.ne("category")].index)[1:] # using 1: to skip hosp1y
numerical

['agey', 'shlt', 'bmi']

In [179]:
binary = [col for col in list(df_full_train.dtypes.index) if col not in numerical][1:] # using 1: to skip hosp1y
binary
df_full_train[binary].nunique()

ragender    2
vigact      2
dtype: int64

In [180]:
df_full_train[numerical]

agey  shlt        bmi
0      85.0   NaN  22.222221
1      65.0   1.0  23.781212
2      69.0   3.0  30.477968
3      88.0   3.0        NaN
4      86.0   4.0        NaN
...     ...   ...        ...
61077  65.0   4.0  45.196281
61078  65.0   4.0        NaN
61079  51.0   4.0  25.153149
61080  77.0   3.0  33.792473
61081  63.0   4.0  22.491348

[61082 rows x 3 columns]

In [181]:
df_full_train[numerical].corrwith(df_full_train.hosp1y)

agey    0.088948
shlt    0.132034
bmi    -0.005099
dtype: float64

In [182]:
for col in binary:
    print("\t", col, "->", df_full_train[col].unique())

	 ragender -> ['2.Woman', '1.Man']
Categories (2, object): ['1.Man' < '2.Woman']
	 vigact -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']


In [258]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.metrics import roc_auc_score

## Preprocessing

In [225]:
train_dicts = df_train[binary + numerical].to_dict(orient="records")

In [226]:
dv = DictVectorizer(sparse=False)

In [227]:
X_train = dv.fit_transform(train_dicts)

In [228]:
X_train[:10]

array([[82.        , 20.45184135,  0.        ,  1.        ,  5.        ,
         0.        ,  1.        ,  0.        ],
       [61.        , 25.390625  ,  0.        ,  1.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [61.        ,         nan,  1.        ,  0.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [64.        , 30.4218483 ,  1.        ,  0.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [82.        , 19.65056229,  0.        ,  1.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [65.        , 25.43268585,  1.        ,  0.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [52.        , 30.11027908,  0.        ,  1.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [52.        , 30.11027908,  0.        ,  1.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [49.        , 32.03125   

In [229]:
imputer = SimpleImputer(strategy='median')
X_train = imputer.fit_transform(X_train)

In [230]:
X_train[:10]

array([[82.        , 20.45184135,  0.        ,  1.        ,  5.        ,
         0.        ,  1.        ,  0.        ],
       [61.        , 25.390625  ,  0.        ,  1.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [61.        , 26.98600197,  1.        ,  0.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [64.        , 30.4218483 ,  1.        ,  0.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [82.        , 19.65056229,  0.        ,  1.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [65.        , 25.43268585,  1.        ,  0.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [52.        , 30.11027908,  0.        ,  1.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [52.        , 30.11027908,  0.        ,  1.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [49.        , 32.03125   

In [231]:
scaler = MinMaxScaler(feature_range = (0, 1))
scaler.fit_transform(X_train)

array([[0.68085106, 0.13366202, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.45744681, 0.18813377, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.45744681, 0.2057298 , 1.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.38297872, 0.23710078, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.39361702, 0.11756048, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.76595745, 0.18353852, 0.        , ..., 0.        , 1.        ,
        0.        ]])

In [244]:
val_dicts = df_val[binary + numerical].to_dict(orient="records")

In [245]:
X_val = dv.transform(val_dicts)

In [246]:
X_val[:10]

array([[54.        , 30.80125046,  0.        ,  1.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [64.        , 21.54508972,  1.        ,  0.        ,  3.        ,
         0.        ,  0.        ,  1.        ],
       [45.        , 24.88888931,  0.        ,  1.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [68.        , 25.390625  ,  1.        ,  0.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [67.        , 22.52150726,  0.        ,  1.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [70.        ,         nan,  0.        ,  1.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [62.        ,         nan,  0.        ,  1.        ,  3.        ,
         0.        ,  0.        ,  1.        ],
       [70.        ,         nan,  0.        ,  1.        ,  5.        ,
         0.        ,  1.        ,  0.        ],
       [70.        , 27.9421463 

In [247]:
X_val = imputer.transform(X_val)

In [248]:
X_val[:10]

array([[54.        , 30.80125046,  0.        ,  1.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [64.        , 21.54508972,  1.        ,  0.        ,  3.        ,
         0.        ,  0.        ,  1.        ],
       [45.        , 24.88888931,  0.        ,  1.        ,  3.        ,
         0.        ,  1.        ,  0.        ],
       [68.        , 25.390625  ,  1.        ,  0.        ,  4.        ,
         0.        ,  0.        ,  1.        ],
       [67.        , 22.52150726,  0.        ,  1.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [70.        , 26.92743874,  0.        ,  1.        ,  4.        ,
         0.        ,  1.        ,  0.        ],
       [62.        , 26.92743874,  0.        ,  1.        ,  3.        ,
         0.        ,  0.        ,  1.        ],
       [70.        , 26.92743874,  0.        ,  1.        ,  5.        ,
         0.        ,  1.        ,  0.        ],
       [70.        , 27.9421463 

In [249]:
scaler.transform(X_val)

array([[0.38297872, 0.24780965, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.4893617 , 0.14571988, 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.28723404, 0.18259994, 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.41489362, 0.22690896, 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.4787234 , 0.20508389, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.4893617 , 0.21627549, 0.        , ..., 0.        , 1.        ,
        0.        ]])

## Logistic Regression

In [250]:
from sklearn.linear_model import LogisticRegression

In [ ]:
col_name = [categorical + numerical]

In [ ]:
def train(df_train, y_train, C=1.0, col_names):

    train_dicts = df_train[col_names].to_dict(orient="records")
    
    dv = DictVectorizer()
    X_train = dv.fit_transform(train_dicts)

    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000)
    model.fit(X_train, y_train)

    return dv, model

In [251]:
type(X_train)

numpy.ndarray

In [252]:
y_train.shape

(45811,)

In [255]:
C=1
model = LogisticRegression(solver='liblinear', C=C, max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(C=1, max_iter=1000, solver='liblinear')

In [257]:
y_pred = model.predict_proba(X_val)[:, 1]

In [259]:
print("ROC AUC = %.3f" % roc_auc_score(y_val, y_pred))

ROC AUC = 0.645
